#!/bin/sh

bail ()
{
    rc=$?
    if [ $rc -ne 0 ] ; then
        echo "$1"
        exit $rc
    fi
}

printf "Creating macrodir...\n"
macrodir="$( sed -r -e '/^AC_CONFIG_MACRO_DIR\(\[(.*)\]\)/!d;'  \
                    -e 's//\1/;'                                \
                    configure.ac                                \
           )"
mkdir -p "${macrodir}"

printf "Running autoreconf...\n"
autoreconf -f -i -Wall
bail "autoreconf failed!"

# Cleanup the useless stuff... :-(
rm -rf autom4te.cache

printf "Done. You may now run:\n    ./configure\n"
