#!/bin/sh

bail ()
{
    rc=$?
    if [ $rc -ne 0 ] ; then
        echo "$1"
        exit $rc
    fi
}

printf "Running libtoolize...\n"
libtoolize --copy --force
bail "libtoolize failed!"

printf "Running aclocal...\n"
aclocal -Wall --force
bail "aclocal failed!"

printf "Running autoconf...\n"
autoconf -Wall --force
bail "autoconf failed!"

printf "Running autoheader...\n"
autoheader -Wall --force
bail "autoheader failed!"

printf "Running automake...\n"
automake --foreign --add-missing --copy -Wall --force
bail "automake failed!"

# Cleanup the mess... :-(
rm -rf autom4te.cache

printf "Done. You may now run:\n    ./configure\n"
