SRCS += gpio.c

SRCS_$(CONFIG_ADC_CLASS) += adc.c
SRCS_$(CONFIG_HAVE_I2C) += i2c.c
SRCS_$(CONFIG_HAVE_LED) += led.c
SRCS_$(CONFIG_PWM_CLASS) += pwm.c
SRCS_$(CONFIG_HAVE_SPI) += spi.c
SRCS_$(CONFIG_UART_CLASS) += uart.c

include $(BASE)/tools/submake.mk
