SRCS_$(CONFIG_9DOF_GYRO) 		+= 9dof_gyro.c
SRCS_$(CONFIG_HMC5883) 			+= px4_hmc5883.c
SRCS_$(CONFIG_MS5611) 			+= px4_ms5611.c
SRCS_$(CONFIG_DISCOVERY_ACCEL) 	+= discovery_accel.c
SRCS_$(CONFIG_MPU6000)			+= px4_mpu6000.c

include $(BASE)/tools/submake.mk
