SRCS += fault.c
SRCS += init.c
SRCS += semaphore.c
SRCS += class.c
SRCS += collection.c
SRCS += symbol_table.c
SRCS += symbol_table_array.c
SRCS += system.c

DIRS += sched/

include $(BASE)/tools/submake.mk
