SRCS += kernel_task.c
SRCS += sched_generic.c
SRCS += sched_api.c
SRCS += sched_end.c
SRCS += sched_interrupts.c
SRCS += sched_new.c
SRCS += sched_start.c
SRCS += sched_switch.c
SRCS += sched_tasks.c
SRCS += sched_asm.S

include $(BASE)/tools/submake.mk
