SRCS_$(CONFIG_MM_ALLOCATOR_BUDDY) += buddy_mm_free.c
SRCS_$(CONFIG_MM_ALLOCATOR_BUDDY) += buddy_mm_init.c
SRCS_$(CONFIG_MM_ALLOCATOR_BUDDY) += buddy_mm_malloc.c
SRCS_$(CONFIG_MM_ALLOCATOR_BUDDY) += buddy_mm_space.c
SRCS_$(CONFIG_MM_ALLOCATOR_BITFIELD) += bitfield_mm_free.c
SRCS_$(CONFIG_MM_ALLOCATOR_BITFIELD) += bitfield_mm_init.c
SRCS_$(CONFIG_MM_ALLOCATOR_BITFIELD) += bitfield_mm_malloc.c
SRCS_$(CONFIG_MM_ALLOCATOR_BITFIELD) += bitfield_mm_space.c

include $(BASE)/tools/submake.mk
