SRCS_$(CONFIG_HAVE_USART) += usart.c
SRCS_$(CONFIG_HAVE_I2C) += i2c.c
SRCS_$(CONFIG_HAVE_SPI) += spi.c
SRCS_$(CONFIG_DISCOVERY_LED) += discovery_led.c
SRCS_$(CONFIG_PX4_LED) += px4_led.c
SRCS_$(CONFIG_PERFCOUNTER) += perfcounter.c

DIRS_$(CONFIG_HAVE_USBDEV) += usb/

include $(BASE)/tools/submake.mk
