SRCS += main.c
SRCS += task_creation.c
SRCS += string.c
SRCS += stdlib.c
SRCS += mm.c
SRCS += cooperate.c
SRCS += shared_mem.c
SRCS += buf_stream.c
SRCS += regression.c
SRCS += init.c

include $(BASE)/tools/submake.mk
