/*
 * Copyright (C) 2014 F4OS Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ARCH_CHIP_PERIPH_H_INCLUDED
#define ARCH_CHIP_PERIPH_H_INCLUDED

enum stm32f4_periph_id {
    STM32F4_PERIPH_GPIOA = 0,
    STM32F4_PERIPH_GPIOB,
    STM32F4_PERIPH_GPIOC,
    STM32F4_PERIPH_GPIOD,
    STM32F4_PERIPH_GPIOE,
    STM32F4_PERIPH_GPIOF,
    STM32F4_PERIPH_GPIOG,
    STM32F4_PERIPH_GPIOH,
    STM32F4_PERIPH_GPIOI,
    STM32F4_PERIPH_TIM1,
    STM32F4_PERIPH_TIM2,
    STM32F4_PERIPH_TIM3,
    STM32F4_PERIPH_TIM4,
    STM32F4_PERIPH_TIM5,
    STM32F4_PERIPH_TIM6,
    STM32F4_PERIPH_TIM7,
    STM32F4_PERIPH_TIM8,
    STM32F4_PERIPH_TIM9,
    STM32F4_PERIPH_TIM10,
    STM32F4_PERIPH_TIM11,
    STM32F4_PERIPH_TIM12,
    STM32F4_PERIPH_TIM13,
    STM32F4_PERIPH_TIM14,
    STM32F4_PERIPH_SPI1,
    STM32F4_PERIPH_SPI2,
    STM32F4_PERIPH_SPI3,
    STM32F4_PERIPH_I2C1,
    STM32F4_PERIPH_I2C2,
    STM32F4_PERIPH_I2C3,
    STM32F4_PERIPH_USART1,
    STM32F4_PERIPH_USART2,
    STM32F4_PERIPH_USART3,
    STM32F4_PERIPH_USART4,
    STM32F4_PERIPH_USART5,
    STM32F4_PERIPH_USART6,
    STM32F4_PERIPH_CAN1,
    STM32F4_PERIPH_CAN2,
    STM32F4_PERIPH_SDIO,
    STM32F4_PERIPH_ETH,
    STM32F4_PERIPH_DCMI,
    STM32F4_PERIPH_FSMC,
    STM32F4_PERIPH_DMA1,
    STM32F4_PERIPH_DMA2,
    STM32F4_PERIPH_ADC1,
    STM32F4_PERIPH_ADC2,
    STM32F4_PERIPH_ADC3,
    STM32F4_PERIPH_DAC,
    STM32F4_PERIPH_USBFS,
    STM32F4_PERIPH_USBHS,
    STM32F4_PERIPH_WWDG,
    STM32F4_PERIPH_PWR,
    STM32F4_PERIPH_SYSCFG,
    STM32F4_PERIPH_CRC,
    STM32F4_PERIPH_RNG,
    STM32F4_PERIPH_HASH,
    STM32F4_PERIPH_CRYP,
    STM32F4_PERIPH_CCMRAM,
    NUM_STM32F4_PERIPH,
};

#endif
